export {RiHome2Line,} from 'react-icons/ri'
export {AiOutlineUser} from 'react-icons/ai'
export {FiSettings} from 'react-icons/fi'
export {HiOutlineMail} from 'react-icons/hi'
export {BsInstagram} from 'react-icons/bs'
export {ImLinkedin2} from 'react-icons/im'